const getRandomValue = (min = 0, max = 1) => {
  // 1. Create a promice 
  // 2. Using Math.random() to create a random number between [min;max)
  // 3. Sending the random number to  Promise.resolve()
  let promise = new Promise((resolve) => {
    let randNumber = Math.random() * (max - min) + min;
    resolve(randNumber);
  });
  return promise;
};

describe('getRandomValue', () => {
  it('returns a promise of a random integer', () => {
    getRandomValue().then(value => assert.isNumber(value));
  });
});


describe('getFourRandomValues', () => {
  const getFourRandomValues = (min, max) => {
    // 1. Create a promice 
    // 2. Create an empty array
    // 3. Add values using for loop and Array.prototype.push()

    let promise = new Promise((resolve) => {
      let array = [];
      for(let i = 0 ; i< 4; i++) {
          array.push(Math.random() * (max - min) + min);
      }
      resolve(array);
    });
    return promise;
  };

  it('returns an array of four integers, generated by getRandomValue()', () => {
    getFourRandomValues().then(values => assert.lengthOf(values, 4));
  });
});
